{% set name = "idds-client" %}
{% set version = "0.7.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/idds-client-{{ version }}.tar.gz
  sha256: 47879184a433423fae728bbb6758f99e7f2dfeff65215d5fe9c909ca95fbc22a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flask
    - idds-common =={{ version }}
    - idds-workflow =={{ version }}
    - python >=3.6
    - requests
    - stomp.py
    - tabulate
    - urllib3

test:
  imports:
    - idds
    - idds.client

about:
  home: https://pypi.org/project/idds-client/
  summary: intelligent Data Delivery Service(iDDS) Package
  dev_url: https://github.com/HSF/iDDS
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - yesw2000
